### ISSUE TITLE
Undocumented dependency? `async-timeout`

### ISSUE THREAD

**Issue by jusdino** [gremlin/gremlin-python#88]
Hey, just trying out this lib for the first time and am running straight into an issue that looks like a missed dependency:
Traceback (most recent call last):
```
  File "/var/task/basic_query.py", line 10, in <module>
    from gremlin_python.driver.aiohttp.transport import AiohttpTransport, AiohttpHTTPTransport
  File "/var/task/gremlin_python/driver/aiohttp/transport.py", line 21, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'
```

Installing `async-timeout` resolved this. Looking at your `setup.py`, I'm now seeing that you don't list `aiohttp` at all, either so I'm not sure what your intended use here is. Should they be listed as extras?

**Comment by sewhyte** [comment]
Hi @jusdino : I think you're looking for this project: https://github.com/goblin-ogm/aiogremlin
