### ISSUE TITLE
Unusable with uvloop

### ISSUE THREAD

**Issue by alfechner** [gremlin/gremlin-python#94]
I'd like to use the client in my [Connexion](https://github.com/spec-first/connexion) server application. Connexion is an **async**, [Starlette](https://www.starlette.io/)-based framework just like [FastAPI](https://fastapi.tiangolo.com/).

I use the [uvicorn](https://www.uvicorn.org/) server in dev and [Gunicorn](https://gunicorn.org/) with the `uvicorn.workers.UvicornWorker` worker class in prod. This is a pretty standard approach to service Python web services.

Both approaches use [uvloop](https://github.com/MagicStack/uvloop) as event loop.

I'm struggling to make the `gremlin-python` client working with this event loop implementation. I'm wondering if it's possible at all. The way I understand the code is that `AiohttpTransport` or `AiohttpHTTPTransport` is pretty much all that is supported.

I'd appreciate some guidance and explanation about the concept if possible. Thanks a lot!

**Comment by sewhyte** [comment]
Hello.

I believe you're looking for the project here: https://github.com/apache/tinkerpop
